# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_time"
version = "2.0.1"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John Urban"
description = "date and time conversion, formatting and computation "
categories = ["time"]
keywords = ["fortran", "date", "time", "Julian", "Unix Epoch", "calendar" ]
homepage = "https://github.com/urbanjost/M_time.git"
[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   # new default with v0.8.0
   # force module naming rules to avoid collisions with other packages
   module-naming = true
   # traditional where user can use any module name
   #module-naming = false

# new section with v0.8.0
[fortran]
   implicit-typing = false
   implicit-external = false
   source-form = "free"
   # traditional pre-version8 compatibility
   #implicit-typing = true
   #implicit-external = true
   #source-form = "default"

[[test]]
   name="runTests"
   source-dir="test/"
   main="test_suite_M_time.F90"
   [test.dependencies]
   M_framework    = { git = "https://github.com/urbanjost/M_framework.git" }
   #M_framework = {namespace = "GPF"}
   # ln -f -s $HOME/github/GLINKS GLINKS
   #M_framework  = { path = "GLINKS/M_framework" }

[[executable]]
   name="now"
   source-dir="app/"
   main="now.f90"
   [executable.dependencies]
   M_kracken95  = { git = "https://github.com/urbanjost/M_kracken95.git" }
   M_strings    = { git = "https://github.com/urbanjost/M_strings.git" }
   #M_kracken95  = { namespace = "GPF" }
   #M_strings    = { namespace = "GPF" }
   #M_kracken95  = { path = "GLINKS/M_kracken95" }
   #M_strings    = { path = "GLINKS/M_strings" }

[[executable]]
   name="sec2days"
   source-dir="app/"
   main="sec2days.f90"
   [executable.dependencies]
   M_kracken95    = { git = "https://github.com/urbanjost/M_kracken95.git" }
   M_strings    = { git = "https://github.com/urbanjost/M_strings.git" }
   #M_kracken95  = { namespace = "GPF" }
   #M_strings    = { namespace = "GPF" }
   #M_kracken95  = { path = "GLINKS/M_kracken95" }
   #M_strings    = { path = "GLINKS/M_strings" }

[[executable]]
   name="days2sec"
   source-dir="app/"
   main="days2sec.f90"
   [executable.dependencies]
   M_kracken95    = { git = "https://github.com/urbanjost/M_kracken95.git" }
   M_strings    = { git = "https://github.com/urbanjost/M_strings.git" }
   #M_kracken95  = { namespace = "GPF" }
   #M_strings    = { namespace = "GPF" }
   #M_kracken95  = { path = "GLINKS/M_kracken95" }
   #M_strings    = { path = "GLINKS/M_strings" }

[[executable]]
   name="month"
   source-dir="app/"
   main="month.f90"
   [executable.dependencies]
   M_kracken95    = { git = "https://github.com/urbanjost/M_kracken95.git" }
   M_strings    = { git = "https://github.com/urbanjost/M_strings.git" }
   #M_kracken95  = { namespace = "GPF" }
   #M_strings    = { namespace = "GPF" }
   #M_kracken95  = { path = "GLINKS/M_kracken95" }
   #M_strings    = { path = "GLINKS/M_strings" }

[[executable]]
   name="today"
   source-dir="app/"
   main="today.f90"
   [executable.dependencies]
   M_kracken95    = { git = "https://github.com/urbanjost/M_kracken95.git" }
   #M_kracken95  = { namespace = "GPF" }
   #M_kracken95  = { path = "GLINKS/M_kracken95" }
