# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_time"
version = "1.0.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John Urban"
description = "date and time conversion, formatting and computation "
categories = ["time"]
keywords = ["fortran", "date", "time", "Julian", "Unix Epoch", "calendar" ]
homepage = "https://github.com/urbanjost/M_time.git"

[[test]]
name="runTests"
source-dir="test/"
main="test_suite_M_time.F90"
[test.dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }

[[executable]]
name="now"
source-dir="app/"
main="now.f90"
[executable.dependencies]
M_kracken95  = { git = "https://github.com/urbanjost/M_kracken95.git" }
M_strings    = { git = "https://github.com/urbanjost/M_strings.git" }

[[executable]]
name="sec2days"
source-dir="app/"
main="sec2days.f90"
[executable.dependencies]
M_kracken95    = { git = "https://github.com/urbanjost/M_kracken95.git" }
M_strings    = { git = "https://github.com/urbanjost/M_strings.git" }

[[executable]]
name="days2sec"
#source-dir="app/"
main="days2sec.f90"
[executable.dependencies]
M_kracken95    = { git = "https://github.com/urbanjost/M_kracken95.git" }
M_strings    = { git = "https://github.com/urbanjost/M_strings.git" }

[[executable]]
name="month"
source-dir="app/"
main="month.f90"
[executable.dependencies]
M_kracken95    = { git = "https://github.com/urbanjost/M_kracken95.git" }
[[executable]]

name="today"
source-dir="app/"
main="today.f90"
[executable.dependencies]
M_kracken95    = { git = "https://github.com/urbanjost/M_kracken95.git" }
