name = "M_time"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John Urban"
description = "date and time conversion formatting and computation "

[[test]]
name="runTests"
source-dir="test/test_suite"
main="test_suite_M_time.f90"

[[executable]]
name="box_month"
source-dir="test/demos/box_month"
main="box_month.f90"

[[executable]]
name="d2j"
source-dir="test/demos/d2j"
main="d2j.f90"

[[executable]]
name="d2o"
source-dir="test/demos/d2o"
main="d2o.f90"

[[executable]]
name="d2u"
source-dir="test/demos/d2u"
main="d2u.f90"

[[executable]]
name="d2w"
source-dir="test/demos/d2w"
main="d2w.f90"

[[executable]]
name="date_to_julian"
source-dir="test/demos/date_to_julian"
main="date_to_julian.f90"

[[executable]]
name="date_to_unix"
source-dir="test/demos/date_to_unix"
main="date_to_unix.f90"

[[executable]]
name="days2sec"
source-dir="test/demos/days2sec"
main="days2sec.f90"

[[executable]]
name="dow"
source-dir="test/demos/dow"
main="dow.f90"

[[executable]]
name="easter"
source-dir="test/demos/easter"
main="easter.f90"

[[executable]]
name="fmtdate"
source-dir="test/demos/fmtdate"
main="fmtdate.f90"

[[executable]]
name="fmtdate_usage"
source-dir="test/demos/fmtdate_usage"
main="fmtdate_usage.f90"

[[executable]]
name="guessdate"
source-dir="test/demos/guessdate"
main="guessdate.f90"

[[executable]]
name="j2d"
source-dir="test/demos/j2d"
main="j2d.f90"

[[executable]]
name="julian_to_date"
source-dir="test/demos/julian_to_date"
main="julian_to_date.f90"

[[executable]]
name="mo2d"
source-dir="test/demos/mo2d"
main="mo2d.f90"

[[executable]]
name="mo2v"
source-dir="test/demos/mo2v"
main="mo2v.f90"

[[executable]]
name="moon_fullness"
source-dir="test/demos/moon_fullness"
main="moon_fullness.f90"

[[executable]]
name="now"
source-dir="test/demos/now"
main="now.f90"

[[executable]]
name="o2d"
source-dir="test/demos/o2d"
main="o2d.f90"

[[executable]]
name="ordinal_seconds"
source-dir="test/demos/ordinal_seconds"
main="ordinal_seconds.f90"

[[executable]]
name="ordinal_to_date"
source-dir="test/demos/ordinal_to_date"
main="ordinal_to_date.f90"

[[executable]]
name="phase_of_moon"
source-dir="test/demos/phase_of_moon"
main="phase_of_moon.f90"

[[executable]]
name="sec2days"
source-dir="test/demos/sec2days"
main="sec2days.f90"

[[executable]]
name="u2d"
source-dir="test/demos/u2d"
main="u2d.f90"

[[executable]]
name="unix_to_date"
source-dir="test/demos/unix_to_date"
main="unix_to_date.f90"

[[executable]]
name="v2mo"
source-dir="test/demos/v2mo"
main="v2mo.f90"

[[executable]]
name="w2d"
source-dir="test/demos/w2d"
main="w2d.f90"
