name = "M_time"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John Urban"

[[test]]
name="runTests"
source-dir="test"
main="test_suite_M_time.f90"

[[executable]]
name="box_month"
source-dir="PROGRAMS/demo_box_month"
main="box_month.f90"

[[executable]]
name="d2j"
source-dir="PROGRAMS/demo_d2j"
main="d2j.f90"

[[executable]]
name="d2o"
source-dir="PROGRAMS/demo_d2o"
main="d2o.f90"

[[executable]]
name="d2u"
source-dir="PROGRAMS/demo_d2u"
main="d2u.f90"

[[executable]]
name="d2w"
source-dir="PROGRAMS/demo_d2w"
main="d2w.f90"

[[executable]]
name="date_to_julian"
source-dir="PROGRAMS/demo_date_to_julian"
main="date_to_julian.f90"

[[executable]]
name="date_to_unix"
source-dir="PROGRAMS/demo_date_to_unix"
main="date_to_unix.f90"

[[executable]]
name="days2sec"
source-dir="PROGRAMS/demo_days2sec"
main="days2sec.f90"

[[executable]]
name="dow"
source-dir="PROGRAMS/demo_dow"
main="dow.f90"

[[executable]]
name="easter"
source-dir="PROGRAMS/demo_easter"
main="easter.f90"

[[executable]]
name="fmtdate"
source-dir="PROGRAMS/demo_fmtdate"
main="fmtdate.f90"

[[executable]]
name="fmtdate_usage"
source-dir="PROGRAMS/demo_fmtdate_usage"
main="fmtdate_usage.f90"

[[executable]]
name="guessdate"
source-dir="PROGRAMS/demo_guessdate"
main="guessdate.f90"

[[executable]]
name="j2d"
source-dir="PROGRAMS/demo_j2d"
main="j2d.f90"

[[executable]]
name="julian_to_date"
source-dir="PROGRAMS/demo_julian_to_date"
main="julian_to_date.f90"

[[executable]]
name="mo2d"
source-dir="PROGRAMS/demo_mo2d"
main="mo2d.f90"

[[executable]]
name="mo2v"
source-dir="PROGRAMS/demo_mo2v"
main="mo2v.f90"

[[executable]]
name="moon_fullness"
source-dir="PROGRAMS/demo_moon_fullness"
main="moon_fullness.f90"

[[executable]]
name="now"
source-dir="PROGRAMS/demo_now"
main="now.f90"

[[executable]]
name="o2d"
source-dir="PROGRAMS/demo_o2d"
main="o2d.f90"

[[executable]]
name="ordinal_seconds"
source-dir="PROGRAMS/demo_ordinal_seconds"
main="ordinal_seconds.f90"

[[executable]]
name="ordinal_to_date"
source-dir="PROGRAMS/demo_ordinal_to_date"
main="ordinal_to_date.f90"

[[executable]]
name="phase_of_moon"
source-dir="PROGRAMS/demo_phase_of_moon"
main="phase_of_moon.f90"

[[executable]]
name="sec2days"
source-dir="PROGRAMS/demo_sec2days"
main="sec2days.f90"

[[executable]]
name="u2d"
source-dir="PROGRAMS/demo_u2d"
main="u2d.f90"

[[executable]]
name="unix_to_date"
source-dir="PROGRAMS/demo_unix_to_date"
main="unix_to_date.f90"

[[executable]]
name="v2mo"
source-dir="PROGRAMS/demo_v2mo"
main="v2mo.f90"

[[executable]]
name="w2d"
source-dir="PROGRAMS/demo_w2d"
main="w2d.f90"

