M_time: m_time__duplicate::string_to_value Interface Reference
m_time__duplicate::string_to_value Interface Reference
Public Member Functions
subroutine a2d (chars, valu, ierr, onerr)
subroutine a2r (chars, valu, ierr)
subroutine a2i (chars, valu, ierr)
Member Function/Subroutine Documentation
a2d()
subroutine m_time__duplicate::string_to_value::a2d (character(len=*), intent(in) chars, doubleprecision, intent(out) valu, integer, intent(out) ierr, class(*), intent(in), optional onerr)
Parameters
[in] chars subroutine returns doubleprecision value from string
References m_time__duplicate::decodebase(), m_time__duplicate::gen, and m_time__duplicate::substitute().
a2i()
subroutine m_time__duplicate::string_to_value::a2i (character(len=*), intent(in) chars, integer, intent(out) valu, integer, intent(out) ierr)
Parameters
[in] chars subroutine returns integer value from string
References m_time__duplicate::a2d(), and m_time__duplicate::gen.
a2r()
subroutine m_time__duplicate::string_to_value::a2r (character(len=*), intent(in) chars, real, intent(out) valu, integer, intent(out) ierr)
NAME
string_to_value(3f) - [M_strings:NUMERIC] subroutine returns numeric value from string (LICENSE:PD)
SYNOPSIS
subroutine string_to_value(chars,valu,ierr)
 character(len=*),intent(in)              :: chars   ! input string
 integer|real|doubleprecision,intent(out) :: valu
 integer,intent(out)                      :: ierr
DESCRIPTION
returns a numeric value from a numeric character string.
works with any g-format input, including integer, real, and exponential. If the input string begins with "B", "Z", or "O" and otherwise represents a positive whole number it is assumed to be a binary, hexadecimal, or octal value. If the string contains commas they are removed. If the string is of the form NN:MMM... or NN#MMM then NN is assumed to be the base of the whole number.
if an error occurs in the READ, IOSTAT is returned in IERR and value is set to zero. if no error occurs, IERR=0.
OPTIONS
CHARS input string to read numeric value from
RETURNS
VALU numeric value returned. May be INTEGER, REAL, or DOUBLEPRECISION. IERR error flag (0 == no error)
EXAMPLES
Sample Program:
 program demo_string_to_value
 use M_strings, only: string_to_value
 character(len=80) :: string
    string=' -40.5e-2 '
    call string_to_value(string,value,ierr)
    write(*,*) 'value of string ['//trim(string)//'] is ',value
 end program demo_string_to_value
AUTHOR
John S. Urban
LICENSE
Public Domain
Parameters
[in] chars subroutine returns real value from string
References m_time__duplicate::a2d(), and m_time__duplicate::gen.
The documentation for this interface was generated from the following file:
/home/runner/work/M_time/M_time/src/M_time__duplicate.f90