M_time: m_time__oop Module Reference
m_time__oop Module Reference
Data Types
interface date_time
Functions/Subroutines
type(date_time) function construct_from_dat (dat)
type(date_time) function construct_from_jd (jd)
type(date_time) function construct_from_uet (uet)
integer function, dimension(8), private dt2d_ (self)
real(kind=realtime) function, private epoch_ (self)
character(len=:) function, allocatable, private format (self, fmt)
real(kind=realtime) function, private mjd_ (self)
real(kind=realtime) function, private julian_ (self)
integer function, private ordinal (self)
integer function, private weekday (self)
type(date_time) function, private delta (self, year, month, day, tz, hour, minute, second, millisecond, week, duration)
subroutine, private init_dt (self, year, month, day, tz, hour, minute, second, millisecond, type, dat)
type(date_time) function plus_seconds (self, seconds)
type(date_time) function minus_seconds (self, seconds)
real(kind=realtime) function minus_date_time (self, other)
logical function eq (self, other)
logical function lt (self, other)
logical function gt (self, other)
logical function le (self, other)
logical function ge (self, other)
logical function ne (self, other)
Variables
integer, parameter dp =kind(0.0d0)
Detailed Description
NAME
M_time__oop(3fm) - [M_time::INTRO::OOPS] OOP interface for M_time(3fm) (LICENSE:MIT)
SYNOPSIS
use M_time__oop, only : date_time ! the type includes the following operators: ! operator(+) ! operator(-) ! operator(>) ! operator(<) ! operator(<=) ! operator(>=) ! operator(==) ! operator(/=)
TYPE(date_time) :: mydate
mydateyear mydatemonth mydateday mydatetz mydatehour mydateminute mydatesecond mydatemillisecond
call mydateinit()
mydateformat('') mydateordinal() mydateweekday() mydateepoch() mydatejulian() mydatemjd() dat=mydatedatout() mydatedelta(year=NN, month=NN, day=NN, tz=NN, hour=NN, minute=NN, second=NN, millisecond=NN, week=NN, duration='DD-HH:MM:SS.XX')
DESCRIPTION
An object-oriented interface to the M_time module. The following example program demonstrates and documents the interface
EXAMPLES
sample program
program demo_M_time__oop ! ! This is an example using the object-oriented class/type model ! This is essentially the same functionality as the procedures ! in the procedural module M_time(3fm), but allows for Object ! Oriented syntax: ! use M_time__oop,only : date_time ! The type includes the operators ... ! operator(+) ! operator(-) ! operator(>) ! operator(<) ! operator(<=) ! operator(>=) ! operator(==) ! operator(/=) implicit none integer,parameter :: dp=kind(0.0d0) integer :: dat(8) TYPE(date_time) :: event TYPE(date_time) :: otherdate TYPE(date_time) :: answer
character(len=*),parameter :: iso_fmt='Y-M-DTh:m:s.xz' ! DIFFERENT INITIALIZATION STYLES ! (Still debating on how best to do this) write(,) write(*,'(a)')'Various initialization styles'
! DEFINE type(date_time) WITH CONSTRUCTOR otherdate=date_time() print *,'DEFAULT CONSTRUCTOR format() ',& & otherdateformat() print *,'DEFAULT CONSTRUCTOR format("") ',& & otherdateformat("") print *,'DEFAULT CONSTRUCTOR format(user-specified) ',& & otherdateformat(iso_fmt) print *,'DEFAULT CONSTRUCTOR format("USA") ',& & otherdateformat("USA")
otherdate=date_time(1492,10,12,0,0,0,0,0) print *,'DEFAULT CONSTRUCTOR setting values ',& & otherdateformat()
otherdate=date_time(2016,6,11) print *,'DEFAULT CONSTRUCTOR with partial values ',& & otherdateformat()
otherdate=date_time(year=2016,month=6,day=11,tz=-240,& & hour=21,minute=09,second=11,millisecond=500) print *,'DEFAULT CONSTRUCTOR with values by name ',& & otherdateformat()
otherdate=date_time([1776,7,4,0,0,0,0,0]) print *,'CONSTRUCTOR with a dat array ',& & otherdateformat()
otherdate=date_time([1776,7,4]) print *,'CONSTRUCTOR with a partial dat array ',& & otherdateformat()
! the init() method supports several methods ! initialize to current time using INIT call otherdateinit() ! initialize to current time using INIT call otherdateinit(type="now")
! initialize to beginning of Unix Epoch Time call otherdateinit(type="epoch") ! Note ! currently, DATE_TIME DATE array is set to Unix Epoch ! start USING LOCAL TIMEZONE ! whereas default constructor is using default of Unix Epoch ! start using Z time (GMT or UTC time)
! initialize with a DAT array using INIT, ! compatible with DATE_AND_TIME VALUES(8) call otherdateinit(dat=[1970,1,1,0,0,0,0,0]) ! using INIT with ordered values call otherdateinit(2016,6,11,-300,23,1,0,0) ! using INIT with names call otherdateinit(year=2016,month=6,day=11,& & tz=-300,hour=23,minute=1,second=0,millisecond=0) ! ! take current date and exercise the OOP interface ! initialize to current time using INIT call eventinit() write(,) write(,)'Print members of type(DATE_TIME)' ! show derived type write(<em>,404)'EVENT=',event 404 format(1x,a,i0,(",",i0:))
! MEMBERS (basic time values are all integers) ! print members of type write(*,101)'year Year................... ',eventyear write(*,101)'month Month.................. ',eventmonth write(*,101)'day Day.................... ',eventday write(*,101)'tz Timezone............... ',eventtz write(*,101)'hour Hour................... ',eventhour write(*,101)'minute Minute................. ',eventminute write(*,101)'second Second................. ',eventsecond write(*,101)'millisecond Millisecond............ ',eventmillisecond
! PRINT METHODS OF TYPE write(,)'Print methods of type(DATE_TIME)' write(*,101)'ordinal Ordinal day of year.... ', eventordinal() write(*,101)'weekday Weekday................ ', eventweekday() 101 format(1x,a,i0) ! DOUBLE PRECISION VALUES EASILY MANIPULATED MATHEMATICALLY write(*,202)'epoch Unix epoch time........ ', eventepoch() write(*,202)'julian Julian date............ ', eventjulian() write(*,202)'mjd Modiied Julian date.... ', eventmjd() 202 format(1x,a,g0)
! FORMATTED STRINGS (many strings possible. ! Takes the same format string as fmtdate(3f)) write(,) write(,'(a)')' Formatted Strings (format("STRING") & & – see fmtdate(3f) for format descriptions' ! abbreviated month name l Dec write(*,303)'Short month............ ',& & eventformat("%l") ! ! full month name L December write(*,303)'Month.................. ',& & eventformat("%L") ! ! first three characters of weekday w Sat write(*,303)'Short week............. ',& & eventformat("%w") ! ! weekday name W Saturday write(*,303)'Week .................. ',& & eventformat("%W") ! ! with no percent (%) characters write(*,303)'Calendar Time ......... ',& & eventformat("Y-M-D h:m:s.x z") ! ! keywords with no percent (%) characters write(*,303)'Calendar Time ......... ',& & eventformat('"year-month-day & & hour:minute:second.millisecond timezone"') ! write(*,)eventformat('Longer format.......... & &"%W, %L %d, %Y %H:%m:%s %N"') ! a nice friendly format ! 303 format(1x,a,'"',a,'"')
! convert date_time to integer array ! (maybe to use with module M_TIME base procedures) dat=eventdatout() write(,) write(*,404)'DAT=',dat
! OVERLOADED OPERATORS (add and subtract) ! a date_time object can have seconds added answer=event+1*86400.0_dp ! ! a nice friendly format write(,)answerformat('TOMORROW="%W, %L %d, %Y %H:%m:%s %N"') ! ! a date_time object can have seconds subtracted answer=event-1*86400.0_dp ! a nice friendly format write(,)answerformat('YESTERDAY="%W, %L %d, %Y %H:%m:%s %N"') ! ! if both operands are DATE_TIME objects a subtraction ! finds the time in seconds between the two dates write(,)'DIFFERENCE (subtracting one date_time from another)=',& & answer-event
! OVERLOADED OPERATORS (logical comparisons) ! NOTE COMPARISONS ARE PERFORMED BY ! CONVERTING TIMES TO INTEGER SECONDS write(,)'> ',event==event ,event<event ,event>event & & ,event<=event ,event>=event ,event/=event ! write(,)'> ',event==answer ,event<answer ,event>answer & & ,event<=answer ,event>=answer ,event/=answer ! write(,)'> ',answer==event ,answer<event ,answer>event & & ,answer<=event ,answer>=event ,answer/=event
! DELTA easily lets you change dates by common increments write(,) write(<em>,404)'DELTA tests starting with date ',eventdelta() ! write(*,) eventformat(" & &%W, %L %d, %Y %H:%m:%s %N")
write(,)'Remember years and months are not constant units'
answer=eventdelta(year=1) write(,)answerformat(& & "FOR %%DELTA(YEAR=+1) %W, %L %d, %Y %H:%m:%s %N") answer=eventdelta(year=-1) write(,)answerformat(& & "FOR %%DELTA(YEAR=-1) %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(month=24) write(,)answerformat(& & "FOR %%DELTA(MONTH=+24) %W, %L %d, %Y %H:%m:%s %N") ! answer=eventdelta(month=-24) write(,)answerformat(& & "FOR %%DELTA(MONTH=-24) %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(week=1) write(,)answerformat(& & "FOR %%DELTA(WEEK=+1) %W, %L %d, %Y %H:%m:%s %N") ! answer=eventdelta(week=-1) write(,)answerformat(& & "FOR %%DELTA(WEEK=-1) %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(day=1) write(,)answerformat(& & "FOR %%DELTA(DAY=+1) %W, %L %d, %Y %H:%m:%s %N") ! answer=eventdelta(day=-1) write(,)answerformat(& & "FOR %%DELTA(DAY=-1) %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(hour=4) write(,)answerformat(& ! & "FOR %%DELTA(HOUR=+4) %W, %L %d, %Y %H:%m:%s %N") answer=eventdelta(hour=-4) write(,)answerformat(& & "FOR %%DELTA(HOUR=-4) %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(minute=180) write(,)answerformat(& & "FOR %%DELTA(MINUTE=+180) %W, %L %d, %Y %H:%m:%s %N") ! answer=eventdelta(minute=-180) write(,)answerformat(& & "FOR %%DELTA(MINUTE=-180) %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(second=1800) write(,)answerformat(& & "FOR %%DELTA(SECOND=+1800) %W, %L %d, %Y %H:%m:%s %N") ! answer=eventdelta(second=-1800) write(,)answerformat(& & "FOR %%DELTA(SECOND=-1800) %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(millisecond=10000) write(,)answerformat(& & "FOR %%DELTA(MILLISECOND=+10000) %W, %L %d, %Y %H:%m:%s %N") ! answer=eventdelta(millisecond=-10000) write(,)answerformat(& & "FOR %%DELTA(MILLISECOND=-10000) %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(year=3,month=2,day=100,hour=200,& & week=-1,minute=300,second=1000,millisecond=-10000) write(,)answerformat(& ! &"FOR %%DELTA(year=3,month=2,day=100,hour=200,& &week=-1,minute=300,second=1000,millisecond=100000)& & %W, %L %d, %Y %H:%m:%s %N")
answer=eventdelta(duration="1-20:30:40.50") write(,)answerformat(& & "FOR %%DELTA(DURATION='1-20:30:40.50')& & %W, %L %d, %Y %H:%m:%s %N")
end program demo_M_time__oop
Sample output:
Various initialization styes DEFAULT CONSTRUCTOR format() 1970-01-01T00:00:00.000+00:00 DEFAULT CONSTRUCTOR format("") 1970-01-01T00:00:00.000+00:00 DEFAULT CONSTRUCTOR format(user-specified) 1970-01-01T00:00:00.000+00:00 DEFAULT CONSTRUCTOR format("USA") Thursday, January 1st, 1970 12:00:00 AM DEFAULT CONSTRUCTOR setting values 1492-10-12T00:00:00.000+00:00 DEFAULT CONSTRUCTOR with partial values 2016-06-11T00:00:00.000+00:00 DEFAULT CONSTRUCTOR with values by name 2016-06-11T21:09:11.500-04:00 CONSTRUCTOR with a dat array 1776-07-04T00:00:00.000+00:00 CONSTRUCTOR with a partial dat array 1776-07-04T20:00:00.000-04:00
Print members of type(DATE_TIME) EVENT=2020,10,24,-240,21,49,54,105 year Year................... 2020 month Month.................. 10 day Day.................... 24 tz Timezone............... -240 hour Hour................... 21 minute Minute................. 49 second Second................. 54 millisecond Millisecond............ 105 Print methods of type(DATE_TIME) ordinal Ordinal day of year.... 298 weekday Weekday................ 6 epoch Unix epoch time........ 1603590594.1049695 julian Julian date............ 2459147.5763206594 mjd Modified Julian date... 59147.9763206594
Formatted Strings (format("STRING") – see fmtdate(3f) for format descriptions Short month............ "Oct" Month.................. "October" Short week............. "Sat" Week .................. "Saturday" Calendar Time ......... "2020-10-24 21:49:54.105 -04:00" Calendar Time ......... ""2020-10-24 21:49:54.105 -0400"" Longer format.......... "Saturday, October 24th, 2020 9:49:54 PM"
DAT=2020,10,24,-240,21,49,54,105 TOMORROW="Sunday, October 25th, 2020 9:49:54 PM" YESTERDAY="Friday, October 23rd, 2020 9:49:54 PM" DIFFERENCE (subtracting one date_time from another)= -86400.000000000000
T F F T T F F F T F T T F T F T F T
DELTA tests starting with date 2020,10,24,-240,21,49,54,105 Saturday, October 24th, 2020 9:49:54 PM Remember years and months are not constant units FOR DELTA(YEAR=+1) Sunday, October 24th, 2021 9:49:54 PM FOR DELTA(YEAR=-1) Thursday, October 24th, 2019 9:49:54 PM FOR DELTA(MONTH=+24) Wednesday, October 26th, 2022 9:49:54 PM FOR DELTA(MONTH=-24) Wednesday, October 24th, 2018 9:49:54 PM FOR DELTA(WEEK=+1) Saturday, October 31st, 2020 9:49:54 PM FOR DELTA(WEEK=-1) Saturday, October 17th, 2020 9:49:54 PM FOR DELTA(DAY=+1) Sunday, October 25th, 2020 9:49:54 PM FOR DELTA(DAY=-1) Friday, October 23rd, 2020 9:49:54 PM FOR DELTA(HOUR=+4) Sunday, October 25th, 2020 1:49:54 AM FOR DELTA(HOUR=-4) Saturday, October 24th, 2020 5:49:54 PM FOR DELTA(MINUTE=+180) Sunday, October 25th, 2020 12:49:54 AM FOR DELTA(MINUTE=-180) Saturday, October 24th, 2020 6:49:54 PM FOR DELTA(SECOND=+1800) Saturday, October 24th, 2020 10:19:54 PM FOR DELTA(SECOND=-1800) Saturday, October 24th, 2020 9:19:54 PM FOR DELTA(MILLISECOND=+10000) Saturday, October 24th, 2020 9:50:04 PM FOR DELTA(MILLISECOND=-10000) Saturday, October 24th, 2020 9:49:44 PM FOR DELTA(year=3,month=2,day=100,hour=200,week=-1,minute=300, second=1000,millisecond=100000) Thursday, April 4th, 2024 11:06:24 AM FOR DELTA(DURATION='1-20:30:40.50') Monday, October 26th, 2020 6:20:34 PM
AUTHOR
John S. Urban, 2015
LICENSE
MIT
Function/Subroutine Documentation
construct_from_dat()
type(date_time) function m_time__oop::construct_from_dat (integer, dimension(:), intent(in) dat) private
construct_from_jd()
type(date_time) function m_time__oop::construct_from_jd (real(kind=realtime), intent(in) jd) private
References construct_from_dat(), and construct_from_jd().
construct_from_uet()
type(date_time) function m_time__oop::construct_from_uet (integer, intent(in) uet) private
References construct_from_dat(), and construct_from_uet().
delta()
type(date_time) function, private m_time__oop::delta (class(date_time), intent(in) self, integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional tz, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, integer, intent(in), optional week, character(len=*), intent(in), optional duration) private
References construct_from_dat(), delta(), and dt2d_().
dt2d_()
integer function, dimension(8), private m_time__oop::dt2d_ (class(date_time), intent(in) self) private
epoch_()
real(kind=realtime) function, private m_time__oop::epoch_ (class(date_time), intent(in) self) private
References dt2d_().
eq()
logical function m_time__oop::eq (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References dt2d_(), and eq().
format()
character(len=:) function, allocatable, private m_time__oop::format (class(date_time), intent(in) self, character(len=*), intent(in), optional fmt) private
References dt2d_(), and m_time__duplicate::upper().
ge()
logical function m_time__oop::ge (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References dt2d_(), and ge().
gt()
logical function m_time__oop::gt (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References dt2d_(), and gt().
init_dt()
subroutine, private m_time__oop::init_dt (class(date_time) self, integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional tz, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, character(len=*), intent(in), optional type, integer, dimension(8), intent(in), optional dat) private
References construct_from_dat(), and dt2d_().
julian_()
real(kind=realtime) function, private m_time__oop::julian_ (class(date_time), intent(in) self) private
References dt2d_().
le()
logical function m_time__oop::le (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References dt2d_(), and le().
lt()
logical function m_time__oop::lt (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References dt2d_(), and lt().
minus_date_time()
real(kind=realtime) function m_time__oop::minus_date_time (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References dt2d_().
minus_seconds()
type(date_time) function m_time__oop::minus_seconds (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds) private
References construct_from_dat(), and dt2d_().
mjd_()
real(kind=realtime) function, private m_time__oop::mjd_ (class(date_time), intent(in) self) private
References dt2d_().
ne()
logical function m_time__oop::ne (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References dt2d_(), and ne().
ordinal()
integer function, private m_time__oop::ordinal (class(date_time), intent(in) self) private
References dt2d_().
plus_seconds()
type(date_time) function m_time__oop::plus_seconds (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds) private
References construct_from_dat(), and dt2d_().
weekday()
integer function, private m_time__oop::weekday (class(date_time), intent(in) self) private
References dt2d_(), and weekday().
Variable Documentation
dp
integer, parameter m_time__oop::dp =kind(0.0d0)