M_time: m_time__oop::date_time Interface Reference
m_time__oop::date_time Interface Reference
Public Member Functions
procedure datout (self)
procedure epoch (self)
procedure julian (self)
procedure mjd (self)
procedure ordinal (self)
procedure weekday (self)
procedure format (self, fmt)
procedure delta (self, year, month, day, tz, hour, minute, second, millisecond, week, duration)
procedure init (self, year, month, day, tz, hour, minute, second, millisecond, type, dat)
generic operator (self, seconds)
generic operator (self, other)
generic operator (self, other)
generic operator (self, other)
generic operator (self, other)
generic operator (self, other)
generic operator (self, other)
generic operator (self, seconds)
generic operator (self, other)
type(date_time) function construct_from_dat (dat)
Public Attributes
integer year =1970
integer month =1
integer day =1
integer tz =0
integer hour =0
integer minute =0
integer second =0
integer millisecond =0
Private Member Functions
procedure, private plus_seconds (self, seconds)
procedure, private eq (self, other)
procedure, private lt (self, other)
procedure, private gt (self, other)
procedure, private ge (self, other)
procedure, private le (self, other)
procedure, private ne (self, other)
procedure, private minus_seconds (self, seconds)
procedure, private minus_date_time (self, other)
Member Function/Subroutine Documentation
construct_from_dat()
type(date_time) function m_time__oop::date_time::construct_from_dat (integer, dimension(:), intent(in) dat)
References m_time__oop::construct_from_dat().
datout()
procedure m_time__oop::date_time::datout (class(date_time), intent(in) self)
delta()
procedure m_time__oop::date_time::delta (class(date_time), intent(in) self, integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional tz, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, integer, intent(in), optional week, character(len=*), intent(in), optional duration)
epoch()
procedure m_time__oop::date_time::epoch (class(date_time), intent(in) self)
eq()
procedure, private m_time__oop::date_time::eq (class(date_time), intent(in) self, type(date_time), intent(in) other) private
format()
procedure m_time__oop::date_time::format (class(date_time), intent(in) self, character(len=*), intent(in), optional fmt)
ge()
procedure, private m_time__oop::date_time::ge (class(date_time), intent(in) self, type(date_time), intent(in) other) private
gt()
procedure, private m_time__oop::date_time::gt (class(date_time), intent(in) self, type(date_time), intent(in) other) private
init()
procedure m_time__oop::date_time::init (class(date_time) self, integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional tz, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, character(len=*), intent(in), optional type, integer, dimension(8), intent(in), optional dat)
julian()
procedure m_time__oop::date_time::julian (class(date_time), intent(in) self)
le()
procedure, private m_time__oop::date_time::le (class(date_time), intent(in) self, type(date_time), intent(in) other) private
lt()
procedure, private m_time__oop::date_time::lt (class(date_time), intent(in) self, type(date_time), intent(in) other) private
minus_date_time()
procedure, private m_time__oop::date_time::minus_date_time (class(date_time), intent(in) self, type(date_time), intent(in) other) private
minus_seconds()
procedure, private m_time__oop::date_time::minus_seconds (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds) private
mjd()
procedure m_time__oop::date_time::mjd (class(date_time), intent(in) self)
ne()
procedure, private m_time__oop::date_time::ne (class(date_time), intent(in) self, type(date_time), intent(in) other) private
operator() [1/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, type(date_time), intent(in) other)
References m_time__oop::eq().
operator() [2/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, type(date_time), intent(in) other)
References m_time__oop::lt().
operator() [3/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, type(date_time), intent(in) other)
References m_time__oop::gt().
operator() [4/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, type(date_time), intent(in) other)
References m_time__oop::ge().
operator() [5/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, type(date_time), intent(in) other)
References m_time__oop::le().
operator() [6/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, type(date_time), intent(in) other)
References m_time__oop::ne().
operator() [7/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, type(date_time), intent(in) other)
References m_time__oop::construct_from_dat(), and m_time__oop::minus_date_time().
operator() [8/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds)
References m_time__oop::plus_seconds().
operator() [9/9]
generic m_time__oop::date_time::operator (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds)
References m_time__oop::minus_seconds().
ordinal()
procedure m_time__oop::date_time::ordinal (class(date_time), intent(in) self)
plus_seconds()
procedure, private m_time__oop::date_time::plus_seconds (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds) private
weekday()
procedure m_time__oop::date_time::weekday (class(date_time), intent(in) self)
Member Data Documentation
day
integer m_time__oop::date_time::day =1
hour
integer m_time__oop::date_time::hour =0
millisecond
integer m_time__oop::date_time::millisecond =0
minute
integer m_time__oop::date_time::minute =0
month
integer m_time__oop::date_time::month =1
second
integer m_time__oop::date_time::second =0
tz
integer m_time__oop::date_time::tz =0
year
integer m_time__oop::date_time::year =1970
The documentation for this interface was generated from the following file:
/home/runner/work/M_time/M_time/src/M_time__oop.f90