# from https://github.com/gha3mi/setup-fortran-conda
name: multi-platform fpm test using conda setup

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: ${{ matrix.os }}_${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gfortran, ifx, lfortran, flang-new]
        include:
        - os: ubuntu-latest
          extra-packages: ""
        - os: windows-latest
          extra-packages: ""
        - os: macos-latest
          extra-packages: ""
        exclude:
          - os: macos-latest
            compiler: flang-new
          - os: macos-latest
            compiler: ifx
          - os: windows-latest
            compiler: lfortran
          - os: windows-latest
            compiler: flang-new
    env:
      TZ: UTC+04:00
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: fortran
          channels: conda-forge, defaults

      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@v0.2.0
        with:
          compiler: ${{ matrix.compiler }}
          platform: ${{ matrix.os }}
          extra-packages: ${{ matrix.extra-packages }}

# ENVIRONMENT VARIABLES FOR COMPILERS
#  FPM_FC            sets the path to the Fortran compiler used for the build, ==> --compiler
#  FPM_FFLAGS        sets the arguments for the Fortran compiler               ==> --flag
#  FPM_CC            sets the path to the C compiler used for the build        ==> --c-compiler
#  FPM_CFLAGS        sets the arguments for the C compiler                     ==> --c-flag
#  FPM_CXX           sets the path to the C++ compiler used for the build,     ==> --cxx-compiler
#  FPM_CXXFLAGS      sets the arguments for the C++ compiler                   ==> --cxx-flag
#  FPM_AR            sets the path to the archiver used for the build,         ==> --archiver
#  FPM_LDFLAGS       sets additional link arguments for creating executables   ==> --link-flag
#
      - name: Set environment for lfortran
        if: matrix.compiler == 'lfortran'
        run: |
          echo "FPM_FFLAGS='--no-style-warnings' --cpp" >> $GITHUB_ENV

      - name: Set environment for gfortran and windows
        if: matrix.compiler == 'gfortran' && matrix.os == 'windows-latest'
        run: |
          echo "end" >_empty.f90
          gfortran -cpp -dM -E _empty.f90
          gfortran --version
          echo "FPM_FFLAGS=-D_WIN32" >> $env:GITHUB_ENV

      - name: Set environment for gfortran and not windows
        if: matrix.compiler == 'gfortran' && matrix.os != 'windows-latest'
        run: |
          echo "end" >_empty.f90
          gfortran -cpp -dM -E _empty.f90
          gfortran --version

      - name: Set environment for flang-new
        if: matrix.compiler == 'flang-new'
        run: |
          echo "end" >_empty.f90
          flang-new -cpp -dM -E _empty.f90
          flang-new --version
          echo "FPM_FFLAGS='-cpp'" >> $GITHUB_ENV

      - name: Set environment for ifx and windows
        if: matrix.compiler == 'ifx' &&  matrix.os == 'windows-latest'
        run: |
          echo "end" >_empty.f90
          ifx -E -fpp empty.f90 -dryrun 2>&1 | perl -lne 'print for /-D(\S+)/'
          #ifx /logo
          #ifx /help
          echo "FPM_FFLAGS=/fpp" >> $env:GITHUB_ENV

      - name: Set environment for ifx and not windows
        if: matrix.compiler == 'ifx' &&  matrix.os != 'windows-latest'
        run: |
          echo "end" >_empty.f90
          ifx -E -fpp empty.f90 -dryrun 2>&1 | perl -lne 'print for /-D(\S+)/'
          ifx --version

# RUN TESTS

      - name: fpm test (debug)
        if: matrix.os != 'windows-latest'
        run: |
          fpm test --compiler ${{ matrix.compiler }} --profile debug --verbose

      - name: fpm test (release)
        if: matrix.os != 'windows-latest'
        run: |
          fpm test --compiler ${{ matrix.compiler }} --profile release -- --brief

      - name: fpm test (debug)
        if: matrix.os == 'windows-latest' && matrix.compiler != 'gfortran'
        run: |
          fpm test --compiler ${{ matrix.compiler }} --profile debug --verbose

      - name: fpm test (release)
        if: matrix.os == 'windows-latest' && matrix.compiler != 'gfortran'
        run: |
          fpm test --compiler ${{ matrix.compiler }} --profile release -- --brief

      - name: fpm test (debug)
        if: matrix.os == 'windows-latest' && matrix.compiler == 'gfortran'
        run: |
          fpm test --compiler ${{ matrix.compiler }} --verbose --fflags="-D_WIN32 -Wall -Wextra -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -fimplicit-none -Werror=implicit-interface" 

      - name: fpm test (release)
        if: matrix.os == 'windows-latest' && matrix.compiler == 'gfortran'
        run: |
          fpm test --compiler ${{ matrix.compiler }} --verbose --fflags="-D_WIN32 -O3 -funroll-loops -Wimplicit-interface -fmax-errors=1 -fcoarray=single -fimplicit-none -Werror=implicit-interface -ffree-form" -- --brief


  summary:
    permissions:
      contents: write
    name: Generate job status table
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate summary from GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          badge_line=""

          mapfile -t job_lines < <(
            curl -s -H "Authorization: token $GH_TOKEN" \
              https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/jobs \
              | jq -r '.jobs[] | select(.name | test(".*_.*")) | [.name, .conclusion] | @tsv'
          )

          for line in "${job_lines[@]}"; do
            name="${line%%$'\t'*}"
            conclusion="${line#*$'\t'}"

            os="${name%%_*}"
            compiler="${name#*_}"
            key="${os}_${compiler}"

            # shields.io escaping
            safe_os="${os//-/'--'}"
            safe_compiler="${compiler//-/'--'}"
            safe_key="${safe_os}_${safe_compiler}"

            if [[ "$conclusion" == "success" ]]; then
              color="brightgreen"
              label="passing"
            elif [[ "$conclusion" == "failure" ]]; then
              color="red"
              label="failing"
            elif [[ "$conclusion" == "cancelled" ]]; then
              color="lightgrey"
              label="cancelled"
            else
              color="lightgrey"
              label="pending"
            fi

            badge="![${key}](https://img.shields.io/badge/${safe_key}-${label}-${color})"
            badge_line="$badge_line $badge"
          done

          echo "$badge_line" > STATUS.md

          mkdir -p status
          mv STATUS.md status/STATUS.md
          cat status/STATUS.md

      - name: Deploy STATUS.md to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages-status
          folder: status
          clean: true
          commit-message: "Deploy status"